name: ticketsprinter
description: Impressão de tickets de venda.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # PERSISTENCIA
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  
  # PERSISTENCIA FIREBASE
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  
  #ICONES
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.10.0

  # web
  json_serializable: ^6.11.1
  http: ^1.5.0
  dio: ^5.4.0
  path_provider: ^2.1.5
  path: ^1.8.0
  
  wakelock_plus: ^1.2.8
  brasil_fields: ^1.18.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  internet_connection_checker: ^3.0.1
  device_info_plus: ^12.1.0
  permission_handler: ^12.0.1
  crypto: ^3.0.6
  flutter_svg: ^2.2.1
  uuid: ^4.5.1
  blue_thermal_printer: ^1.2.3
  webview_flutter: ^4.13.0
  qr_flutter: ^4.1.0
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_empresa.png
    - assets/images/logo.png
    - assets/images/pin_aprovado.jpeg
    - assets/images/Branco-MERCOSUL-2019_PNG_RGB.png
    - assets/images/brasil.png
    - assets/svg/brasil.svg
    - assets/git/versao.txt
    - assets/database/dummy/data.json
    - assets/pages/
        
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 900
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 900          
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 900
