name: ticketsprinter
description: Impressão de tickets de venda.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # PERSISTENCIA
  sqflite: ^2.2.8+4
  shared_preferences: ^2.2.0
  
  # PERSISTENCIA FIREBASE
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  
  #ICONES
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.4.0

  # web
  json_serializable: ^6.6.1
  http: ^0.13.5
  dio: ^5.4.0
  path_provider: ^2.1.0
  path: ^1.8.0
  
  platform_device_id: ^1.0.1
  wakelock: ^0.6.2
  brasil_fields: ^1.12.0
  intl: ^0.18.1
  # flutter_launcher_icons: ^0.12.0
  flutter_launcher_icons: ^0.13.1
  internet_connection_checker: ^1.0.0+1
  device_info_plus: ^8.2.2
  device_information: ^0.0.4
  permission_handler: ^11.0.1
  crypto: ^3.0.2
  flutter_svg: ^1.1.6
  uuid: ^4.1.0
  blue_thermal_printer: ^1.2.3
  webview_flutter: ^4.2.2
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_empresa.png
    - assets/images/logo.png
    - assets/images/pin_aprovado.jpeg
    - assets/images/Branco-MERCOSUL-2019_PNG_RGB.png
    - assets/images/brasil.png
    - assets/svg/brasil.svg
    - assets/git/versao.txt
    - assets/database/dummy/data.json
    - assets/pages/
        
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 900
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 900          
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 900
